# Generated by Django 3.1 on 2020-08-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_tag', models.CharField(max_length=100)),
                ('project_location', models.CharField(max_length=100)),
                ('photo_urlOne', models.TextField(default='urlOne')),
                ('photo_urlTwo', models.TextField(default='urlTwo')),
                ('photo_urlThree', models.TextField(default='urlThree')),
                ('project_description', models.TextField(default='description')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_service', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='swb.project')),
            ],
        ),
    ]
