# Generated by Django 3.1 on 2020-08-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_services',
            field=models.ManyToManyField(to='swb.Service'),
        ),
    ]
