# Generated by Django 3.1 on 2020-08-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swb', '0002_auto_20200828_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='project_service',
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.CharField(default=' ', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_location',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_tag',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
