# Generated by Django 3.1 on 2020-08-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swb', '0003_auto_20200828_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='service_name',
        ),
    ]
