# Generated by Django 3.1 on 2020-08-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swb', '0006_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
