# Generated by Django 3.1 on 2020-08-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swb', '0009_blog_contact_newproject_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(auto_now=True),
        ),
    ]
