# Generated by Django 3.1 on 2020-08-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swb', '0010_auto_20200831_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_subject',
            field=models.CharField(default='SUBJECT', max_length=100),
        ),
    ]
