# Generated by Django 3.1 on 2020-08-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swb', '0010_auto_20200831_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_message',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_subject',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='newproject',
            name='new_project_message',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='newproject',
            name='new_project_subject',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_email',
            field=models.EmailField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_message',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_subject',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
