# Generated by Django 3.1 on 2020-09-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swb', '0011_auto_20200831_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default=' ', max_length=200)),
                ('blog_date', models.DateField(auto_now_add=True)),
                ('blog_body', models.TextField(default='Enter text here')),
            ],
        ),
    ]
