# Generated by Django 3.1 on 2020-09-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swb', '0012_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_tag',
        ),
    ]
