import React, { Component } from "react";
import { BrowserRouter as Router, Link } from "react-router-dom";
import "./AboutUsPage.css";
import "../../index.css";
import Objective from "../../components/Objective/Objective.js";
import IconNumber from "../../../src/components/IconNumber/IconNumber";
import FundingFact from "../../components/FundingFact/FundingFact";
import NavBar from "../../components/NavBar/NavBar";
import Footer from "../../components/Footer/Footer";

class AboutUsPage extends Component {
  constructor() {
    super();

    this.state = { classlist: "AboutUsPage" };
  }

  render() {
    return (
      <div className="container">
        <h1 className="about-title">We are SWB</h1>

        <div class="about-swb">
          <p className="about-swb-p">
            <div
              className="about-img"
              style={{ backgroundImage: "var(--about-swb)", float: "left" }}
            ></div>
            <div className="section-p section-p-one">
              Statistics Without Borders (SWB) is a volunteer Outreach Group of
              the American Statistical Association (ASA) that provides pro bono
              services in statistics and data science. We work to improve
              decision making and knowledge in efforts that promote welfare
              through the proper application of statistical principles and best
              practices, where access to such resources is limited.
            </div>
            <div className="section-p">
              SWB was established in 2008 and provides a focus for pro bono
              statistical consulting within the American statistical
              Association. SWB provides an opportunity for statisticians to
              collaborate with professionals, researchers, and other volunteers
              involved in international health work.
            </div>
            <div className="section-p">
              SWB arose fromt the excitment generated by a topic-contributed
              panel entitled "Statisticians: Speaking Out and Reaching Out on
              Global Health" at the 2008 Joint Statistical Meetings in Denver,
              Colorado. Steve Pierson, Gary Shapiro, Jim Cochran, and Fritz
              Scheuren established Statistics Without Borders as an effort
              within the ASA's Special Interest Group (SIG) on Volunteerism.
              Established in 2005, the SIG on Volunteerism provided pro bono
              statistical consulting internationally, with a focus on human
              rights issues.
            </div>
          </p>
        </div>
        <hr className="about-hr"></hr>
        <h1 className="about-title">How We Started</h1>
        <div className="objective-section objective-section-one">
          <Objective
            year="2008"
            text="It was the excitement around topic-contributed
                    panel at the 2008 Joint Statistical Meetings in Denver, Colorado that sparked the
                    conversation between Gary Shapiro and Fritz Scheuren, which eventually resulted in the
                    formation of Statistics Without Borders (SWB) the same year."
          />
        </div>
        <div className="objective-section">
          <Objective
            year="2010"
            text="In 2010, SWB became an outreach organization of the ASA, and it drafted its first mission and
                    vision having just 130 people on board that year."
          />
        </div>
        <div className="objective-section">
          <Objective
            year="2014"
            text='At the 2014 JSM SWB Business Meeting, two new amendments were introduced to the Charter 
                    by Gary Shapiro. One of the amendments was to extend the definition of a project from global health
                    to include "...the use of statistics to improve the health and well-being of all people."'
          />
        </div>
        <div className="objective-section">
          <Objective
            year="2020"
            text="As of today, more than 1400 volunteers have joined SWB's team!"
          />
        </div>
        <hr className="about-hr"></hr>

        <h1>Our Members</h1>

        <h1 className="number-icons-header">Objectives</h1>
        <div className="number-icons-section">
          <div className="number-icons-objectives">
            <div className="number-icons-icon">
              <IconNumber type="digit" IconNumber box label="01" />
            </div>
            <p className="number-icons-text">
              SWB advocates objective, impartial and sound decision making using
              best statistical practices.
            </p>
          </div>
          <div className="number-icons-objectives">
            <div className="number-icons-icon">
              <IconNumber type="digit" IconNumber two label="02" />
            </div>
            <p className="number-icons-text">
              SWB provides analytical services through client projects for
              public benefit that support goals that are non-religious,
              non-political, and non-personal, with a focus on developing
              countries.
            </p>
          </div>
          <div className="number-icons-objectives">
            <div className="number-icons-icon">
              <IconNumber type="digit" IconNumber three label="03" />
            </div>
            <p className="number-icons-text">
              SWB assists organizations outside of the for-profit sector, with
              priorities given to organizations with limited access to
              statistical resources.
            </p>
          </div>
          <div className="number-icons-objectives">
            <div className="number-icons-icon">
              <IconNumber type="digit" IconNumber four label="04" />
            </div>
            <p className="number-icons-text">
              SWB strengthens its clients and their communities by helping them
              build their capacities in statistics, data science and analytics,
              and promotes best practices in these areas.
            </p>
          </div>
        </div>
        <p className="charter-text">Read the SWB Charter</p>
        <hr className="about-hr"></hr>

        <h1 className="funding-facts-header">Funding Facts</h1>
        <div className="funding-facts-section">
          <div className="funding-facts-fact">
            <FundingFact
              image="var(--about-give-heart)"
              description="SWB does not accept payments or remunerations of any kind."
              imgPositionRight
            />
          </div>
          <div className="funding-facts-fact">
            {" "}
            <FundingFact
              image="var(--about-receive-heart)"
              description="If you would like to donate, the ASA will accept donations earmarked for SWB use."
            />{" "}
          </div>
          <div className="funding-facts-fact">
            {" "}
            <FundingFact
              image="var(--about-no-fees)"
              description="SWB does not collect any volunteer fees or subscription dues."
              imgPositionRight
            />
          </div>
          <div className="funding-facts-fact">
            {" "}
            <FundingFact
              image="var(--about-donate)"
              description="All donations are used 100% for SWB projects and are never used for payments or reimbursements."
            />
          </div>
        </div>
        <p className="funding-facts-readtext">
          Read the Volunteer Code of Conduct and Privacy Policy
        </p>
        <hr className="about-hr"></hr>

        <h1 className="broadgreen-header">SWB and ASA: Broadgreen Solutions</h1>
        <div className="broadgreen-section">
          <p>
            In 2017, the American Statistical Association and SWB explored how
            to move SWB from an outreach group to a more established entity
            within ASA that continues to reflect its unique characteristics. It
            also explicitly recognized that SWB is accountable to the ASA Board
            and that SWB volunteers are expected to adhere to the ASA Ethical
            Guidelines for Statistical Practice. This gives SWB financial
            support from ASA and the ability for SWB to manage limited funds in
            a manner similar to that of the ASA chapters and sections.{" "}
          </p>
          <p>
            SWB is grateful for the assistance and leadership provided by
            Broadgreen Solutions. Broadgreen Solutions, a Certified B Corp that
            provides transformation and advisory services, performed exhaustive
            interviews with SWB Executive Committee members, ASA leadership, SWB
            organizational partners and other non-profit volunteer associations
            to discuss the pros and cons of organizational structure, and
            provided SWB with recommmendations on our future roadmap. SWB also
            thanks ASA Associate Executive Director Steve Porzio for his
            invaluable guidance.
          </p>
          <p>
            SWB has grown substantially over the past decade. This rapid growth
            has enabled SWB to take on more projects, but it has also required
            the Executive Committe to rethink both of its organizational
            structure, policies, and procedures. Ultimately, the goal of the SWB
            Executive Committee is to improve the ability of SWB to be an
            effective organization promoting the greater good through
            statistical practice, and do so as an integral part of the ASA
            organization. SWB looks forward to these positive changes.
          </p>
        </div>
        <hr className="about-hr"></hr>
      </div>
    );
  }
}

export default AboutUsPage;
