import React, { Component } from 'react'
import "./AboutUsPage.css"
import "../../index.css"
import Objective from "../../components/Objective/Objective.js"


class AboutUsPage extends Component {
    constructor() {
        super()

        this.state = { classlist: 'AboutUsPage' }
    }


    render() {


        return (
            <div className="container">
                <h1 className="about-title">We are SWB</h1>

                <div class="about-swb">
                    <p className="about-swb-p">
                        <div className="about-img" style={{ backgroundImage: "var(--about-swb)", float: "left" }}></div>
                        <div className="section-p section-p-one">
                            Statistics Without Borders (SWB) is a volunteer Outreach Group of the
                            American Statistical Association (ASA) that provides pro bono services in
                            statistics and data science. We work to improve decision making and
                            knowledge in efforts that promote welfare through the proper
                            application of statistical principles and best practices, where access to
                            such resources is limited.
                            </div>
                        <div className="section-p">
                            SWB was established in 2008 and provides a focus for pro bono
                            statistical consulting within the American statistical Association. SWB
                            provides an opportunity for statisticians to collaborate with
                            professionals, researchers, and other volunteers involved in
                            international health work.
                            </div>
                        <div className="section-p">
                            SWB arose fromt the excitment generated by a topic-contributed panel
                            entitled "Statisticians: Speaking Out and Reaching Out on Global Health"
                            at the 2008 Joint Statistical Meetings in Denver, Colorado. Steve
                            Pierson, Gary Shapiro, Jim Cochran, and Fritz Scheuren established
                            Statistics Without Borders as an effort within the ASA's Special Interest
                            Group (SIG) on Volunteerism. Established in 2005, the SIG on
                            Volunteerism provided pro bono statistical consulting internationally,
                            with a focus on human rights issues.
                            </div>
                    </p>
                </div>
                <hr className="about-hr"></hr>
                <h1 className="about-title">How We Started</h1>
                <div className="objective-section objective-section-one">
                    <Objective year="2008" text="It was the excitement around topic-contributed
                    panel at the 2008 Joint Statistical Meetings in Denver, Colorado that sparked the
                    conversation between Gary Shapiro and Fritz Scheuren, which eventually resulted in the
                    formation of Statistics Without Borders (SWB) the same year." />
                </div>
                <div className="objective-section">
                    <Objective year="2010" text="In 2010, SWB became an outreach organization of the ASA, and it drafted its first mission and
                    vision having just 130 people on board that year." />
                </div>
                <div className="objective-section">
                    <Objective year="2014" text='At the 2014 JSM SWB Business Meeting, two new amendments were introduced to the Charter 
                    by Gary Shapiro. One of the amendments was to extend the definition of a project from global health
                    to include "...the use of statistics to improve the health and well-being of all people."' />
                </div>
                <div className="objective-section">
                    <Objective year="2020" text="As of today, more than 1400 volunteers have joined SWB's team!" />
                </div>
                <hr className="about-hr"></hr>

            </div>
        )
    }
}

export default AboutUsPage
